# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -std=c++11 -D_REENTRANT
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.calculator
DEPENDENCIES  = .depend.$(MAKEFILE)
BTARGETDIR    = ./
BIN           = $(BTARGETDIR)calculator$(EXESUFFIX)$(EXEEXT)
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O
LDLIBS        = -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = driver$(OBJEXT) Commands/Addition/Add_Command$(OBJEXT) Commands/Division/Div_Command$(OBJEXT) Commands/Multiplication/Mult_Command$(OBJEXT) Commands/Number/Num_Command$(OBJEXT) Commands/Subtraction/Sub_Command$(OBJEXT) Commands/Modulus/Mod_Command$(OBJEXT) Commands/Open_Parenthesis/Open_Paren_Command$(OBJEXT) Commands/Close_Parenthesis/Close_Paren_Command$(OBJEXT) Factory/Stack/Stack_Expr_Command_Factory$(OBJEXT)
SOEXT         = .so
SRC           = driver.cpp Commands/Addition/Add_Command.cpp Commands/Division/Div_Command.cpp Commands/Multiplication/Mult_Command.cpp Commands/Number/Num_Command.cpp Commands/Subtraction/Sub_Command.cpp Commands/Modulus/Mod_Command.cpp Commands/Open_Parenthesis/Open_Paren_Command.cpp Commands/Close_Parenthesis/Close_Paren_Command.cpp Factory/Stack/Stack_Expr_Command_Factory.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = 
DEPLIBS       = $(foreach lib, , $(foreach libpath, ., $(wildcard $(libpath)/lib$(lib).a)))

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(BIN)

$(BIN): $(OBJS) $(DEPLIBS)
	@$(TESTDIRSTART) "$(BTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(BTARGETDIR)"
	$(LINK.cc) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

generated: $(GENERATED_DIRTY)
	@-:

driver$(OBJEXT): driver.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) driver.cpp

Commands/Addition/Add_Command$(OBJEXT): Commands/Addition/Add_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Commands/Addition/Add_Command.cpp

Commands/Division/Div_Command$(OBJEXT): Commands/Division/Div_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Commands/Division/Div_Command.cpp

Commands/Multiplication/Mult_Command$(OBJEXT): Commands/Multiplication/Mult_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Commands/Multiplication/Mult_Command.cpp

Commands/Number/Num_Command$(OBJEXT): Commands/Number/Num_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Commands/Number/Num_Command.cpp

Commands/Subtraction/Sub_Command$(OBJEXT): Commands/Subtraction/Sub_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Commands/Subtraction/Sub_Command.cpp

Commands/Modulus/Mod_Command$(OBJEXT): Commands/Modulus/Mod_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Commands/Modulus/Mod_Command.cpp

Commands/Open_Parenthesis/Open_Paren_Command$(OBJEXT): Commands/Open_Parenthesis/Open_Paren_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Commands/Open_Parenthesis/Open_Paren_Command.cpp

Commands/Close_Parenthesis/Close_Paren_Command$(OBJEXT): Commands/Close_Parenthesis/Close_Paren_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Commands/Close_Parenthesis/Close_Paren_Command.cpp

Factory/Stack/Stack_Expr_Command_Factory$(OBJEXT): Factory/Stack/Stack_Expr_Command_Factory.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Factory/Stack/Stack_Expr_Command_Factory.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(BIN)

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) -Wall -Wextra -pedantic -fsyntax-only $(CHK_SOURCES)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------


depend:
	-$(MPC_ROOT)/depgen.pl  $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

-include $(DEPENDENCIES)
